spring:
  data:
    mongodb:
#      database: ${MONGO_DATABASE}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
          database: bankDb
          port: 27017
          host: localhost
  application:
    name: bank-circle-service
server:
  port: 9700
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka


