spring:
  data:
    mongodb:
      #      database: ${MONGO_DATABASE}
      #      port: ${MONGO_PORT}
      #      host: ${MONGO_HOST}
      database: userDB
      port: 27017
      host: localhost
  application:
    name: product-service
server:
  port: 9500
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka



